### ISSUE TITLE
Provide a hi or mark element

### ISSUE THREAD

**Issue by shaunix** [projectmallard/projectmallard.org#3]
For a very long time, Yelp has supported the hi element in the experimental namespace. This is an inline element that highlights the text with a yellow background. It's useful to show what's new when progressively building on a code sample, for example.

This is a simple element to implement and doesn't obviously fit into any other extension, so we should just add it to the Mallard core. It's similar to the HTML mark element, so maybe it should be named mark. We should recommend style hints for "added" and "deleted" and maybe other common reasons to highlight text.

**Comment by ptomato** [comment]
:+1:

**Comment by shaunix** [comment]
http://projectmallard.org/mep/mep0009.html

**Comment by shaunix** [comment]
Spec finished. Implemented in yelp-xsl. Closing this issue.
http://projectmallard.org/1.1/mal_inline_hi
