### ISSUE TITLE
type attribute for the code element

### ISSUE THREAD

**Issue by vanillajonathan** [projectmallard/projectmallard.org#38]
Provide a `lang` attribute for the `<code>` element.

```xml
<code lang="python">
class Cat(object):
    def talk():
        """Make some noise."""
        print('Meow')
</code>
```

This would semantically declare the language of the code.
Which could be used to apply syntax highlighting.

**Comment by shaunix** [comment]
The current way to do this is with the mime attribute, which takes a MIME type, e.g.:

  <code mime="text/x-python">

This has proven itself cumbersome, because nobody can remember the MIME types, and most MIME types for programming languages are just made up and unregistered. In the future (possibly Mallard 1.1), we'll probably change this to the type attribute, just using a simple string like "python". See:

https://github.com/projectmallard/projectmallard.org/issues/21

**Comment by vanillajonathan** [comment]
Ah, the documentation mentioning the `mime` attribute is here:
http://projectmallard.org/1.0/mal_block_code

I did miss it because I didn't see it on the learning page:
http://projectmallard.org/about/learn/code

Wikipedia which is powered by MediaWiki uses the [SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighligh) extension which does syntax highlighting using the `lang` attribute. It is powered by [Pygments](http://pygments.org/).
It also have a `line` attribute to indicate that the lines should be numbered.

Wikipedia, [GitHub](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code), and [Disqus](https://help.disqus.com/customer/portal/articles/665057-syntax-highlighting) uses simple strings like "python".

**Comment by shaunix** [comment]
http://projectmallard.org/mep/mep0010.html

**Comment by vanillajonathan** [comment]
I would rather see the attribute be named `lang` than `type`.

The [SyntaxHighlight](https://www.mediawiki.org/wiki/Extension:SyntaxHighlight#lang) extension for MediaWiki uses `lang` for the attribute name.

**Comment by shaunix** [comment]
I noted the request for a lang attribute in the Alternatives section of the MEP. I think it's confusing with the same-named attribute used for human languages in various formats (namedspaced or not). I really want to take advantage of Ducktype's shorthand syntax, and I want to do something similar to replace the mime attribute on media elements in 1.2.

**Comment by vanillajonathan** [comment]
Good point @shaunix, as you said; the `lang` attribute is usually used for human language.
The `type` attribute is actually a good choice, since it is used for MIME type in the [`script`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script) element as well as the `link` element.

Example:
```html
<script type="text/javascript" src="script.js"></script>
<link rel="stylesheet" type="text/css" href="theme.css">
```
