### ISSUE TITLE
Make example a formal element

### ISSUE THREAD

**Issue by shaunix** [projectmallard/projectmallard.org#4]
example is the only block container element that can't take a title. Let's just make it a formal element by allowing a title, and whatever else might get added to formal elements down the road (id, info).

**Comment by ptomato** [comment]
:+1:

**Comment by pmkovar** [comment]
+1

**Comment by shaunix** [comment]
Implemented in yelp-xsl master. Will be in 3.20. Still needs spec changes in Mallard 1.1.

**Comment by shaunix** [comment]
Spec and schema updated: http://projectmallard.org/1.1/mal_block_example
