### ISSUE TITLE
CSS, Webkit and HiDPI

### ISSUE THREAD

**Issue by rgaiacs** [projectmallard/projectmallard.org#40]
Hi,

I'm at GUADEC and learning about GNOME documentation and when looking at Mallard I got

![screenshot from 2017-07-31 15-54-03](https://user-images.githubusercontent.com/1506457/28783533-8b44e646-7608-11e7-815c-aab61d250170.png)

Probably this is a CSS issue when you use Webkit and HiDPI. Please let me know if you need more info.

**Comment by shaunix** [comment]
I don't think it has anything to do with HiDPI. It appears to be an issue with WebKit when there's a vertical flexbox as a direct child of a horizontal flexbox. Not sure yet if there's a good CSS fix without inserting an extra wrapper div.

**Comment by shaunix** [comment]
This seems to be a WebKit bug when you have a flexbox child with flex-basis set to 100%, but I failed to create a simple reproducible test case. Setting flex-basis to auto seems to give OK results without the rendering bug, so I've changed to that.
